services:
  mysql:
    image: mysql:8.4.5
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 1


  zookeeper:
    image: bitnami/zookeeper:3.9.1
    container_name: my-zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
#    healthcheck:
#      test: ["CMD-SHELL", "echo ruok | nc localhost 2181 | grep imok"]
#      interval: 10s
#      timeout: 5s
#      retries: 1


  kafka:
    image: bitnami/kafka:3.5.1
    container_name: my-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: my-zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"
#    depends_on:
#      zookeeper:
#        condition: service_healthy
#    healthcheck:
#      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
#      interval: 10s
#      timeout: 5s
#      retries: 1
