services:
  mysql:
    image: mysql:8.4.5
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  zookeeper:
    image: bitnami/zookeeper:3.9.1
    container_name: my-zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
#    healthcheck:
#      test: [ "CMD-SHELL", "/opt/bitnami/zookeeper/bin/zkServer.sh status | grep 'Mode:'" ]
#      interval: 10s
#      timeout: 5s
#      retries: 12       # gives ~2 minutes of retries
#      start_period: 40s # wait before first check

  kafka:
    image: bitnami/kafka:3.5.1
    container_name: my-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: my-zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"
#    depends_on:
#      zookeeper:
#        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "/opt/bitnami/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 > /dev/null 2>&1" ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 30s
