//package org.gul;
//
//import java.util.List;
//import java.util.stream.Collectors;
//
//public class Mersk {
//
//    //Employee -> name, age, dept, sal
//    // print name sal> 15K
//
//    List<String> names = employees.stream().filter(e->e.getSal>15000).map(e->e.getName()).collect(Collectors.toList());
//
//    for(String s : names){
//        System.out.println(s);
//    }
//
//
//    employees.sorted((e1, e2) -> e1.getAge().comparesTo(e2.getAge));
//
//
//    interface A {
//
//        void a1();
//        default a2(){
//            return null;
//        }
//
//    }
//
//
//    interface B {
//
//        void a1();
//        default a2(){
//            return;
//        }
//    }
//
//    class C implements A, B{
//        super.A.a2();
//
//    }
//
//    public static void main(String[] args) {
//
//    }
//
//    class CustService{
//
//        @Autowired
//        @Qualifier("A")
//        private A;
//        private B;
//    }
//
//    // GET /employees
//
//    @RequestMapping("/employees")
//    @RestController
//    class Employees{
//
//        @Autowired
//        private EmployeeService service;
//
//        @GetMapping( produces="app/json")
//        public List<Employees> getEmployees(){
//            List<Employees> employees = service.getEmployees();
//            return employees;
//        }
//
//
//    }
//
//    interface EmployeeService{
//        List<Employee> getEmployees();
//    }
//
//    @Service
//    class EmployeeServiceImpl implements EmployeeService{
//
//        @Autowired
//        private EmployeeRepository repo;
//
//        @Override
//        List<Employees> getEmployees(){
//            List<Employee> employees = repo.findAll();
//        }
//
//    }
//
//
//    @Entity
//    @Getter
//    @Setter
//    class Employee{
//
//        @Id
//        @Autogenerated
//        private Long id;
//
//        private String name;
//        private int age;
//
//        @OneToOne
//        private Dept dept;
//        private double sal;
//
//    }
//
//    @Entity
//    class Dept{
//
//        @ManyToOne(mappedBy="dept")
//        private List<Employee> employees;
//        private String name;
//
//    }
//
//
//    interface EmployeeRepository implement
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//}
